In [1]:
import numpy as np

In [10]:
random=np.random.uniform(0,1)
random

0.15443287280926932

In [22]:
marks=np.random.randint(0,100,20)
marks


array([36, 71, 87, 89, 70, 28, 55, 65, 48, 70, 64, 19, 17, 99,  7, 32, 66,
       85, 40, 77])

In [25]:
aes= np.sort(marks)
aes

array([ 7, 17, 19, 28, 32, 36, 40, 48, 55, 64, 65, 66, 70, 70, 71, 77, 85,
       87, 89, 99])

In [26]:
des=np.flip(aes)
des

array([99, 89, 87, 85, 77, 71, 70, 70, 66, 65, 64, 55, 48, 40, 36, 32, 28,
       19, 17,  7])

In [30]:
#copy

In [34]:
aes[0:5]=68
aes

array([68, 68, 68, 68, 68, 36, 40, 48, 55, 64, 65, 66, 70, 70, 71, 77, 85,
       87, 89, 99])

In [37]:
slice=aes[0:5]
slice

array([68, 68, 68, 68, 68])

In [38]:
deep_copy_aes=np.copy(aes)


In [39]:
deep_copy_aes[:]

array([68, 68, 68, 68, 68, 36, 40, 48, 55, 64, 65, 66, 70, 70, 71, 77, 85,
       87, 89, 99])

In [40]:
deep_copy_aes[0:5]

array([68, 68, 68, 68, 68])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [59]:
np.eye(5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [ ]:
np.eye(5).flatten

In [47]:
np.eye(6).ravel()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [6]:
np.ravel?

In [4]:
np.flatten?

Object `np.flatten` not found.


In [65]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
c=np.ones(3)
c

array([1., 1., 1.])

In [85]:
np.vstack((b,[[10,12,13]]))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 12, 13]])

In [87]:
#np.hstack?

In [88]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
np.vsplit(b,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [94]:
np.hsplit(b,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [97]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [101]:
f=np.random.uniform(1,20,5)

In [102]:
f

array([ 3.72527919,  2.57776558, 17.68875151,  7.23493212, 15.3680054 ])

In [103]:
np.ceil(f)

array([ 4.,  3., 18.,  8., 16.])

In [104]:
np.floor(f)

array([ 3.,  2., 17.,  7., 15.])

In [105]:
np.round(f,decimals=2)

array([ 3.73,  2.58, 17.69,  7.23, 15.37])

In [110]:
g=np.arange(0,25).reshape(5,5)
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
np.min(g,axis=0)

array([0, 1, 2, 3, 4])

In [118]:
np.max(g,axis=0)

array([20, 21, 22, 23, 24])

In [117]:
np.std(g,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [126]:
y=np.arange(1,11,dtype=float,)
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [128]:
y[:]='Nan'

In [129]:
y[6]=200
y

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [130]:
h=np.arange(100,150)
h

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [132]:
np.flip(h)

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [134]:
e=np.arange(1,26).reshape(5,5)
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [137]:
x=np.array([1,0,2,0,0,4,0,8])
x

array([1, 0, 2, 0, 0, 4, 0, 8])

In [138]:
np.where(x>0)

(array([0, 2, 5, 7], dtype=int64),)

In [143]:
p=np.ones((10,10))
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [147]:
p[1:9,1:9]=0
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
o=np.ones((8,8))

o[1::2,1::2]=0
o[0::2,::2]=0
o

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])